### ISSUE TITLE
algo: YLDY displaying negative balance

### ISSUE THREAD

**Issue by PCK1992** [hodgerpodger/staketaxcsv#241] opened 2023-01-30 19:04 UTC
Thank you for this amazing tool! It generally seems to work great but I have one particular issue with yieldly:

![image](https://user-images.githubusercontent.com/17555094/215570520-167cf990-2140-4ec2-8e77-169fe179eebb.png)

I have a negative balance right at the time when I sold all my yieldly - any clue how to solve this issue or is this a bug?

Wallet: J3BW4YTTHFL7CYYMORL2WW44PRM5ZX35QIYMGVAPAH7O7TC4FB2DSE4RGU

**Comment by jumperavocado** [comment] 2023-01-30 22:48
Looks like a bug. I'll push a fix for this when I get a chance.

**Comment by hodgerpodger** [comment] 2023-02-01 00:48
Fix deployed.

**Closed by hodgerpodger** 2023-02-01 00:48 UTC

**Comment by PCK1992** [comment] 2023-02-01 16:50
Damn, that was fast - thank you!

**Comment by jumperavocado** [comment] 2023-02-01 21:54
That's odd, if you open the CSV in e.g. google docs, sum all the YLDY received and substruct all the YLDY sent, you get 0.

**Comment by jumperavocado** [comment] 2023-02-01 22:36
A bit of context. The report you see in the website contains some transactions with an underscore prefix, e.g. _UNSTAKE. These are non taxable events and are there for informational purposes only, in fact when you download the CSV for e.g. Koinly these transactions are ommited. 

The received minus sent YLDY amount add up to 0 in the CSV, so this is fine. I suspect the issue is that there are some untaxable transactions in Yieldly that we are not processing and this throws off the chart (which takes into account all transaction types).

I'll take a look when I get a chance to see if I can make the chart add up too.

**Comment by PCK1992** [comment] 2023-02-02 00:32
Ok, thanks for the explanation! The graph is definitely less important but i was curious how this could happen. Perhaps because it might be missing some tx between other wallets and exchanges.

**Comment by jumperavocado** [comment] 2023-02-04 18:28
Hi @PCK1992, this is unrelated to YLDY, but I'm trying to add support for more apps so that I can tag transactions correctly. I've come accross one of your transactions, looks like an aggregator swap https://algoexplorer.io/tx/group/7nyeKdKDgILEWHKhszkdH7AB0AN0Z5Q2cPkujmY61H4%3D but can't find any information about the app. If you don't mind me asking, is this perhaps a Defly swap?
